### ISSUE TITLE
Collection of issues of demos with OCCT 7.4.0

### ISSUE THREAD

**Issue by rainman110** [tpaviot/pythonocc-demos#17]
- [x] core_display_overlayered_image.py : No Addons Module anymore. @tpaviot What shall we do?
- [x] core_display_overlayered_lines.py : No Addons Module anymore.
- [x] core_display_overlayered_text.py : No Addons Module anymore.

**Comment by tpaviot** [comment]
You can remove it. I don't use it, nobody neverd asked or contributed something related. Moreover, it's a GUI stuff which is a nightmare to maintain (Qt4 Qt5 and so on). Bye bye Addons module and demos. Someone may bring them back to life if he needs them.

**Comment by rainman110** [comment]
I created the branch occt7.4.0 that fixes most of the problems. Please check this!

**Comment by tpaviot** [comment]
Great, I'm on it

**Comment by tpaviot** [comment]
I merged your two commits in my branch, and added two more examples. Everything pass, I still have to check the behaviour and outputs for each of them.

**Comment by rurubino1** [comment]
Hello, nice to meet you... 
Sorry the possibly stupid question, but I cannot run any example.
For example core_helloworld.py
`Traceback (most recent call last):

  File "C:\Users\rurubino\Documents\_RES House Modeling\BIM2BEM\pythonocc-demos-master\examples\core_helloworld.py", line 35, in <module>
    from OCC.Display.SimpleGui import init_display

  File "C:\ProgramData\Anaconda3\lib\site-packages\OCC\Display\SimpleGui.py", line 26, in <module>
    from OCC.Display.OCCViewer import OffscreenRenderer

  File "C:\ProgramData\Anaconda3\lib\site-packages\OCC\Display\OCCViewer.py", line 30, in <module>
    from OCC.Core.Aspect import Aspect_GFM_VER

  File "C:\ProgramData\Anaconda3\lib\site-packages\OCC\Core\Aspect.py", line 145, in <module>
    import OCC.Core.Standard

  File "C:\ProgramData\Anaconda3\lib\site-packages\OCC\Core\Standard.py", line 18, in <module>
    from . import _Standard

ImportError: DLL load failed: La procédure spécifiée est introuvable.`

Any clue?
thanks a lot in advance
